//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_BIBLIOTHEQUES
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livre()
        {
            this.ajouter = new HashSet<ajouter>();
        }
    
        public int id_livre { get; set; }
        public string titre { get; set; }
        public string auteur { get; set; }
        public string editeur { get; set; }
        public Nullable<System.DateTime> annee_publication { get; set; }
        public Nullable<int> nombre_pages { get; set; }
        public Nullable<int> prix { get; set; }
        public Nullable<int> id_dom { get; set; }
        public Nullable<bool> empruneter { get; set; }
        public Nullable<int> id_abonnée { get; set; }
    
        public virtual abonnée abonnée { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajouter> ajouter { get; set; }
        public virtual domaine domaine { get; set; }
    }
}
