//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_BIBLIOTHEQUES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_bibliothequeEntities3 : DbContext
    {
        public gestion_bibliothequeEntities3()
            : base("name=gestion_bibliothequeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abonnée> abonnée { get; set; }
        public virtual DbSet<ajouter> ajouter { get; set; }
        public virtual DbSet<domaine> domaine { get; set; }
        public virtual DbSet<employé> employé { get; set; }
        public virtual DbSet<livre> livre { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
